openapi: 3.0.0
info:
  title: 'Envlog Project CRUD'
  description: 'Envlog Project Application API'
  version: 1.0.0

servers:
  - url: 'http://localhost:3001/'
    description: 'Local development'
  #- url: 'https://ymlwbdaex2.execute-api.eu-central-1.amazonaws.com/dev/' indirizzo di stage dopo deploy ? boooo
  #  description: 'Stage'

paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: 'Register'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterPayload'
      responses:
        '201':
          description: 'Account created'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
        '400':
          description: 'Bad request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '500':
          description: 'Internal server error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
  /auth/login:
    post:
      tags:
        - Auth
      summary: 'Login'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginPayload'
      responses:
        '201':
          description: 'Login succesfull'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: 'Bad request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '500':
          description: 'Internal server error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
  /auth/logout:
    post:
      tags:
        - Auth
      summary: 'Logout'
      responses:
        '200':
          description: 'Logout succesfull'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '400':
          description: 'Bad request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '500':
          description: 'Internal server error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
  /sensors/groups:
    get:
      tags:
        - Sensors
      summary: 'Get sensors by groups'
      responses:
        '200':
          description: 'Get sensors list order by group'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SensorsPayload'
        '400':
          description: 'Bad request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '500':
          description: 'Internal server error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'





components:
  schemas:
    Message:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    RegisterPayload:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
        passwordConfirmation:
          type: string 
      required:
        - username
        - email
        - password
        - passwordConfirmation
    RegisterResponse:
      description: 'Register response'
      type: object
      properties:
        username:
          type: string
        email:
          type: string
    LoginPayload:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
      required:
        - email
        - password
    LoginResponse:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
          format: email
        isAdmin:
          type: boolean
    SensorsPayload:
      type: object
      properties:
        _id:
          type: string
        MCU_ID:
          type: string
        NAME:
          type: string
        Type:
          type: string
        Enabled:
          type: boolean
        Group:
          type: string

